name: Run Python script
on: [push]
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Run Python script
      uses: actions/exec@v2
      with:
        command: python test.py
